-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 10:17:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id_category` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id_prod` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  `discription` LONGTEXT NULL,
  `image_prod` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id_prod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_category` (
  `category_id_category` INT NOT NULL,
  `product_id_prod` INT NOT NULL,
  PRIMARY KEY (`category_id_category`, `product_id_prod`),
  CONSTRAINT `fk_client_has_produit_client`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `mydb`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_produit_produit1`
    FOREIGN KEY (`product_id_prod`)
    REFERENCES `mydb`.`product` (`id_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_client_has_produit_produit1_idx` ON `mydb`.`product_has_category` (`product_id_prod` ASC) VISIBLE;

CREATE INDEX `fk_client_has_produit_client_idx` ON `mydb`.`product_has_category` (`category_id_category` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
